version: '1.0.{build}'
skip_tags: true

environment:
  matrix:
    - PYTHON: "C:\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

install:
  - pip install -U PyInstaller

before_build:

build_script:
  - python -m PyInstaller -F -w kindle.pyw

after_build:
  - ps: cd dist\
  - ps: 7z a ..\kindle.zip kindle.exe

artifacts:
  - path: kindle.zip
    name: kindle

deploy:
  release: kindle-v$(appveyor_build_version)
  description: ''
  provider: GitHub
  auth_token:
    secure: x2VCjhjls6MUIYqj+WN0D5Db4HA3hTIep++8jGWbSQtnGcPMfzj5gWW39ZNg1z/5
  artifact: kindle.zip
  force_update: true
  draft: false
  prerelease: false
  appveyor_repo_tag: false
